apiVersion: v1
kind: Service
metadata:
  name: app-prod-service-nodeport-flask
  namespace: prod
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 5002
      targetPort: 5002

