apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-iranarang-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed

