apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-prod-pvc-redis
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed

