version: "3"
services:
  redis-db:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    user: "1000:1000"
    command: ["--save", "1", "1"]

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: iranarang/api_app:1.0
    ports:
      - "5000:5000"
    volumes:
      - ./config.yaml:/config.yaml
    environment:
      - REDIS_IP=redis-db
    entrypoint: ["python", "flask_api.py"]  

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: iranarang/api_worker:1.0
    volumes:
      - ./src/worker.py:/app/worker.py 
    environment:
      - REDIS_IP=redis-db
    entrypoint: ["python", "worker.py"]  

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    image: iranarang/test_app:1.0
    volumes:
      - ./config.yaml:/config.yaml
    environment:
      - REDIS_IP=redis-db
      - FLASH_ENV=test
    command: ["pytest"] 
